# Generated by Django 2.0 on 2018-09-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_author_book_bookinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(choices=[('science fiction', 'science fiction'), ('Fantasy', 'Fantasy'), ('Western', 'Western'), ('French Poetry', 'French Poetry')], help_text='Select Genre for this book ', to='catalog.Genre'),
        ),
    ]
