# Generated by Django 2.0 on 2018-09-30 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180930_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(help_text='Enter name of the author', on_delete=django.db.models.deletion.CASCADE, to='catalog.Author'),
        ),
    ]
